#+TITLE: sarso

[[tag][file:https://img.shields.io/github/v/tag/lepisma/sarso.svg?style=flat-square]] [[GitHub Workflow Status][file:https://img.shields.io/github/workflow/status/lepisma/sarso/CI.svg?style=flat-square]]

Sarso is not Jira.

Sarso does a local sync of Jira projects to provide better and faster offline
workflows. This includes integration with Org-mode, faster find and create
methods etc. Sarso is not a replacement for the Jira interface but covers what I
need to do on regular basis, faster.

** Installation
There are two programs here:
+ A CLI executable, =sarso= for syncing issues to an sqlite database.
+ An Emacs package for working with the database.

For syncing you need to setup few environment variables for Jira. Here is a
slice from .envrc file.

: export JIRA_BASE="https://company.atlassian.net"
: export JIRA_USER="username"
: export JIRA_TOKEN="token/pass"

** Usage
Here is a workflow for v1 which is a little like maildir sync:

+ Run =sarso= and collect tickets from Jira in an sqlite db. For now, it does full
  sync for a single project. =sarso sync --file db.sqlite --project MAC=
+ Work with the database in Emacs/Org Mode.
+ Add tickets to-sync in database from within Emacs and run =sarso= again to get
  the tickets up on Jira.
